server:
  port: 80


eureka:
  client:
    register-with-eureka: false #服务注册开关，false表示不再将此服务注册到Eureka服务端中
    fetch-registry: true  #服务发现开关
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
feign:
  hystrix:
    enabled: true